/*This file was generated by NativeWind. Do not edit!*/
const {
  NativeWindStyleSheet: _NativeWindStyleSheet
} = require("nativewind");
_NativeWindStyleSheet.create({
  styles: {
    "newCss": {
      "color": "#ef4444",
      "fontSize": 36,
      "lineHeight": 40
    },
    "newCss@0": {
      "elevation": 3,
      "shadowColor": "rgba(0, 0, 0, 0.1)"
    },
    "newCss@1": {
      "shadowOffset": {
        "width": 0,
        "height": 2
      },
      "shadowRadius": 6,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "newCss@2": {
      "shadowOffset": {
        "width": 0,
        "height": 2
      },
      "shadowRadius": 6,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    }
  },
  atRules: {
    "newCss": [[["media", "android"]], [["media", "ios"]], [["media", "web"]]]
  }
});